# Form implementation generated from reading ui file 'd:\work\DataAnalysisApp\ui\folder.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 141)
        Dialog.setMinimumSize(QtCore.QSize(576, 141))
        Dialog.setMaximumSize(QtCore.QSize(576, 141))
        self.comboBox_1 = CheckableComboBox(parent=Dialog)
        self.comboBox_1.setGeometry(QtCore.QRect(100, 20, 291, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        self.comboBox_1.setFont(font)
        self.comboBox_1.setObjectName("comboBox_1")
        self.label_1 = QtWidgets.QLabel(parent=Dialog)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 91, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        self.label_1.setFont(font)
        self.label_1.setLineWidth(1)
        self.label_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_1.setObjectName("label_1")
        self.comboBox = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox.setGeometry(QtCore.QRect(100, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setPlaceholderText("")
        self.comboBox.setDuplicatesEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 71, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(1)
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 60, 161, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(400, 20, 161, 31))
        self.pushButton_1.setObjectName("pushButton_1")

        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "批量处理csv文件数据"))
        self.label_1.setText(_translate("Dialog", " 变量选择："))
        self.comboBox.setItemText(0, _translate("Dialog", "平均值"))
        self.label_2.setText(_translate("Dialog", "算法选择："))
        self.pushButton_2.setText(_translate("Dialog", "开始计算"))
        self.pushButton_1.setText(_translate("Dialog", "选择文件夹"))
from ui.checkablecombobox import CheckableComboBox
